---
title: "Pass-Only Simulation Stats"
author: "Corinne Steuk"
date: "11/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Rlab)
```

## Instantiation

```{r}
state <- list()
state$down <- 1 
state$downyards <- 0 
state$totyards <- 0 
state$totdowns <- 0 
```

## Function
```{r}
play <- function(){
   yardage <- 0
   while ((yardage < 3) | (yardage > 75)){
     yardage <- rlnorm(1, mean = log(10), sd = 1)
     yardage <- round(yardage)
   #Given his pass is of length 'yardage,' 
   #what is the probability that he can complete a pass of this length?
   p_comp <- .97^(yardage)
   complete_check <- rbern(1, prob = p_comp)
   if(complete_check ==1){
     return(yardage)
   }else{
     yardage <- 0 
     return (yardage)
   }
 }
}

drive <-function(){
state$down <- 1 
state$downyards <- 0 
state$totyards <- 0 
state$totdowns <- 0 
#while total yards is less than 75 and down is less than 5
while ((state$totyards < 75) & (state$down <= 4)){
yards <- play()

state$down <- state$down +1 
state$downyards <-  state$downyards + yards
state$totyards <- state$totyards + yards
state$totdowns <-  state$totdowns + 1

if (state$totyards >= 75 ){
  break
}else if(state$downyards >= 10){
  state$down <- 1
  state$downyards <- 0
}else if(state$down > 4){
  break
}

}
return(state)}
```

## Probability of Success
**Out of 10,000 drives, what is the probability they will end in a touchdown? Given they acheived a touchdown, what is the average number of plays it took?**

```{r}
nsim <- 10000
t_yrds <- c(replicate(nsim, 0))
t_plays <- c(replicate(nsim, 0))
for (i in 1:nsim){
  j <- drive()
  t_yrds[i] <- j$totyards
  t_plays[i] <- j$totdowns
}
td <- 0
plays_cnt <- 0
td_idx <- which(t_yrds >= 75)
for (i in t_yrds){
  if (i >= 75){
    td = td +1
  }
}
for (t in td_idx){
   plays_cnt <- plays_cnt + t_plays[t]
}
prob_td <- td/length(t_yrds)
prob_td

#Average Number of Plays to Get a Touchdown
plays_cnt/length(t_plays)

```





